## **Numpy**

In [1]:
import numpy as np

### **1. ndarray**

##### Numpy 기반 데이터 타입인 ndarray 생성 실습

In [2]:
array1 = np.array([1, 2, 3])
print(array1)
print('- array1 type:', type(array1))
print('- array1 shape:', array1.shape)
print('- array1 ndim:', array1.ndim, '\n')

array2 = np.array([[1, 2, 3]])
print(array2)
print('- array2 type:', type(array2))
print('- array2 shape:', array2.shape)
print('- array2 ndim:', array2.ndim, '\n')

array3 = np.array([[1, 2, 3],
                   [1, 2, 3]])
print(array3)
print('- array3 type:', type(array3))
print('- array3 shape:', array3.shape)
print('- array3 ndim:', array3.ndim)

[1 2 3]
- array1 type: <class 'numpy.ndarray'>
- array1 shape: (3,)
- array1 ndim: 1 

[[1 2 3]]
- array2 type: <class 'numpy.ndarray'>
- array2 shape: (1, 3)
- array2 ndim: 2 

[[1 2 3]
 [1 2 3]]
- array3 type: <class 'numpy.ndarray'>
- array3 shape: (2, 3)
- array3 ndim: 2


### **2. ndarray 데이터 타입**

##### 1) ndarray 내에 서로 다른 데이터 타입의 형 변환 실습

In [3]:
array1 = np.array([1, 2, 3])
print(array1)
print('- array1 dtype:', array1.dtype, '\n')

array2 = np.array([1, 2, 'ml'])
print(array2)
print('- array2 dtype:', array2.dtype, '\n')

array3 = np.array([1, 2, 3.0])
print(array3)
print('- array3 dtype:', array3.dtype)

[1 2 3]
- array1 dtype: int64 

['1' '2' 'ml']
- array2 dtype: <U21 

[1. 2. 3.]
- array3 dtype: float64


##### 2) ndarray 데이터 타입 변경 실습 

In [4]:
array1 = np.array([1, 2, 3])
print(array1)
print('- array1 dtype:', array1.dtype, '\n')

array2 = array1.astype('float32')
# array2 = array1.astype(np.float32)
print(array2)
print('- array2 dtype:', array2.dtype)

[1 2 3]
- array1 dtype: int64 

[1. 2. 3.]
- array2 dtype: float32


### **3. ndarray 생성 및 크기 ・ 차원 변경**



##### 1) 특정 크기와 차원을 가진 ndarray 생성 실습

In [5]:
array1 = np.arange(10)
print(array1)
print('- array1 dtype:', array1.dtype)
print('- array1 shape:', array1.shape, '\n')

array2 = np.zeros((2, 3), dtype = 'int32')
print(array2)
print('- array2 dtype:', array2.dtype)
print('- array2 shape:', array2.shape, '\n')

array3 = np.ones((2, 3))
print(array3)
print('- array3 dtype:', array3.dtype)
print('- array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
- array1 dtype: int64
- array1 shape: (10,) 

[[0 0 0]
 [0 0 0]]
- array2 dtype: int32
- array2 shape: (2, 3) 

[[1. 1. 1.]
 [1. 1. 1.]]
- array3 dtype: float64
- array3 shape: (2, 3)


##### 2) ndarray 크기와 차원 변경 실습

In [6]:
array1 = np.arange(10).reshape(2, 5)
# array1 = np.arange(10).reshape((2, 5))
print(array1)
print('- array1 shape:', array1.shape, '\n')

array2 = np.arange(10).reshape(-1, 5)
print(array2)
print('- array2 shape:', array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
- array1 shape: (2, 5) 

[[0 1 2 3 4]
 [5 6 7 8 9]]
- array2 shape: (2, 5)


In [7]:
array1 = np.arange(12).reshape((2, 2, 3))
print(array1.tolist())
print('- array1 shape:', array1.shape)
print('- array1 ndim:', array1.ndim, '\n')

array2 = array1.reshape(-1, 1)
print(array2.tolist())
print('- array2 shape:', array2.shape)
print('- array2 ndim:', array2.ndim, '\n')

array3 = array1.reshape(-1,)
print(array3.tolist())
print('- array3 shape:', array3.shape)
print('- array3 ndim:', array3.ndim)

[[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]
- array1 shape: (2, 2, 3)
- array1 ndim: 3 

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11]]
- array2 shape: (12, 1)
- array2 ndim: 2 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
- array3 shape: (12,)
- array3 ndim: 1
