## **Numpy**

In [1]:
import numpy as np

### **인덱싱(Indexing)**

##### 1-1) 1차원 ndarray 단일 값 추출

In [2]:
array_1d = np.arange(1, 10)
print(array_1d, '\n')

# ndim(1 → 0)
print(f'- array_1d[3] = {array_1d[3]} / ndim = {array_1d[3].ndim}')
print(f'- array_1d[-1] = {array_1d[-1]} / ndim = {array_1d[-1].ndim}')

[1 2 3 4 5 6 7 8 9] 

- array_1d[3] = 4 / ndim = 0
- array_1d[-1] = 9 / ndim = 0


##### 1-2) 2차원 ndarray 단일 값 추출

In [3]:
array_1d = np.arange(1, 10)
array_2d = array_1d.reshape(-1, 3)
print(array_2d, '\n')

# ndim(2 → 0)
print(f'- array_2d[1, 1] = {array_2d[1, 1]} / ndim = {array_2d[1, 1].ndim}')
print(f'- array_2d[-1, -1] = {array_2d[-1, -1]} / ndim = {array_2d[-1, -1].ndim}')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

- array_2d[1, 1] = 5 / ndim = 0
- array_2d[-1, -1] = 9 / ndim = 0


##### 2-1) 1차원 ndarray 슬라이싱(Slicing)

In [4]:
array_1d = np.arange(1, 10)
print(array_1d, '\n')

# ndim(1 → 1)
print(f'- array_1d[0:3] = {array_1d[0:3]} / ndim = {array_1d[0:3].ndim}')
print(f'- array_1d[3:] = {array_1d[3:]} / ndim = {array_1d[3:].ndim}')

[1 2 3 4 5 6 7 8 9] 

- array_1d[0:3] = [1 2 3] / ndim = 1
- array_1d[3:] = [4 5 6 7 8 9] / ndim = 1


##### 2-2) 2차원 ndarray 슬라이싱(Slicing)

In [5]:
array_1d = np.arange(1, 10)
array_2d = array_1d.reshape(-1, 3)
print(array_2d, '\n')

# ndim(2 → 1)
print(f'- array_2d[:1, 1] = {array_2d[:1, 1]} / ndim = {array_2d[:1, 1].ndim}')
print(f'- array_2d[1:, 1] = {array_2d[1:, 1]} / ndim = {array_2d[1:, 1].ndim}', '\n')

# ndim(2 → 2)
print(f'- array_2d[:1, :1] = {array_2d[:1, :1]} / ndim = {array_2d[:1, :1].ndim}')
print(f'- array_2d[1:, 1:] = {array_2d[1:, 1:].tolist()} / ndim = {array_2d[1:, 1:].ndim}')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

- array_2d[:1, 1] = [2] / ndim = 1
- array_2d[1:, 1] = [5 8] / ndim = 1 

- array_2d[:1, :1] = [[1]] / ndim = 2
- array_2d[1:, 1:] = [[5, 6], [8, 9]] / ndim = 2


##### 3) 팬시 인덱싱(Fancy Indexing)

In [6]:
array_1d = np.arange(1, 10)
array_2d = array_1d.reshape(-1, 3)
print(array_2d, '\n')

# ndim(2 → 1)
print(f'- array_2d[[1, 2], 1] = {array_2d[[1, 2], 1]} / ndim = {array_2d[[1, 2], 1].ndim}')
print(f'- array_2d[[1, 2], -1] = {array_2d[[1, 2], -1]} / ndim = {array_2d[[1, 2], -1].ndim}', '\n')

# ndim(2 → 2)
print(f'- array_2d[[1, 2], 0:2] = {array_2d[[1, 2], 0:2].tolist()} / ndim = {array_2d[[1, 2], 0:2].ndim}')
print(f'- array_2d[[1, 2]] = {array_2d[[1, 2]].tolist()} / ndim = {array_2d[[1, 2]].ndim}')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

- array_2d[[1, 2], 1] = [5 8] / ndim = 1
- array_2d[[1, 2], -1] = [6 9] / ndim = 1 

- array_2d[[1, 2], 0:2] = [[4, 5], [7, 8]] / ndim = 2
- array_2d[[1, 2]] = [[4, 5, 6], [7, 8, 9]] / ndim = 2


##### 4) 불린 인덱싱(Boolean Indexing)

In [7]:
array = np.arange(1, 10)
print(array, '\n')

print('- array > 3 =', array > 3)
print('- array[array > 3] =', array[array > 3], '\n')

boolean1 = np.array([False, False, False, True, True, True, True, True, True])
print('- array[boolean1] =', array[boolean1])
boolean2 = array > 3
print('- array[boolean2] =', array[boolean2])

[1 2 3 4 5 6 7 8 9] 

- array > 3 = [False False False  True  True  True  True  True  True]
- array[array > 3] = [4 5 6 7 8 9] 

- array[boolean1] = [4 5 6 7 8 9]
- array[boolean2] = [4 5 6 7 8 9]
