## **Numpy**

In [1]:
import numpy as np

### **1. 행렬 정렬**

##### 1) np.sort(): 원 행렬은 유지한 채, 원 형렬을 정렬한 행렬 반환 

In [2]:
array = np.array([5, 3, 7, 1])
print(array, '\n')

# 오름차순 정렬
array_sort1 = np.sort(array)
print('- array =', array)
print('- array_sort1 =', array_sort1, '\n')

# 내림차순 정렬
array_sort2 = np.sort(array)[::-1]
print('- array =', array)
print('- array_sort2 =', array_sort2)

[5 3 7 1] 

- array = [5 3 7 1]
- array_sort1 = [1 3 5 7] 

- array = [5 3 7 1]
- array_sort2 = [7 5 3 1]


In [3]:
array = np.array([5, 3, 7, 1])
array_2d = array.reshape(-1, 2)
print(array_2d, '\n')

# axis = 0 정렬
array_2d_sort1 = np.sort(array_2d, axis = 0)
print('- array_2d =', array_2d.tolist())
print('- array_2d_sort1 =', array_2d_sort1.tolist(), '\n')

# axis = 1 정렬
array_2d_sort2 = np.sort(array_2d, axis = 1)
print('- array_2d =', array_2d.tolist())
print('- array_2d_sort2 =', array_2d_sort2.tolist())

[[5 3]
 [7 1]] 

- array_2d = [[5, 3], [7, 1]]
- array_2d_sort1 = [[5, 1], [7, 3]] 

- array_2d = [[5, 3], [7, 1]]
- array_2d_sort2 = [[3, 5], [1, 7]]


##### 2) ndarray.sort(): 원 행렬 자체를 정렬해 반환

In [4]:
array = np.array([5, 3, 7, 1])
print(array, '\n')

# 오름차순 정렬
array_sort1 = array.sort()
print('- array =', array)
print('- array_sort1 =', array_sort1, '\n')

# 내림차순 정렬
array_sort2 = array.sort()
print('- array =', array[::-1])
print('- array_sort2 =', array_sort2)

[5 3 7 1] 

- array = [1 3 5 7]
- array_sort1 = None 

- array = [7 5 3 1]
- array_sort2 = None


##### 3) np.argsort(): 정렬된 행렬의 인덱스 반환

In [5]:
array = np.array([5, 3, 7, 1])
print(array, '\n')

# 오름차순 정렬
array_argsort1 = np.argsort(array)
print('- array_argsort1 index =', array_argsort1)
print('- array_argsort1 =', array[array_argsort1], '\n')

# 내림차순 정렬
array_argsort2 = np.argsort(array)[::-1]
print('- array_argsort2 index =', array_argsort2)
print('- array_argsort2 =', array[array_argsort2])

[5 3 7 1] 

- array_argsort1 index = [3 1 0 2]
- array_argsort1 = [1 3 5 7] 

- array_argsort2 index = [2 0 1 3]
- array_argsort2 = [7 5 3 1]


### **2. 선형대수 연산**

##### 1) 행렬 내적(행렬 곱)

In [6]:
A = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 3)
print(A, '\n')

B = np.array([7, 8, 9, 10, 11, 12]).reshape(-1, 2)
print(B)

[[1 2 3]
 [4 5 6]] 

[[ 7  8]
 [ 9 10]
 [11 12]]


In [7]:
dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


##### 2) 전치 행렬

In [8]:
A = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 3)
print(A)

[[1 2 3]
 [4 5 6]]


In [9]:
transpose = np.transpose(A)
print(transpose)

[[1 4]
 [2 5]
 [3 6]]
